#!/usr/bin/env sh
# Generates modules/data/FAQContent.lua from FAQ.md -- one page for
# "What's new" (the newest changelog entry) plus one page per FAQ
# question. Wired into release.sh, so the in-game FAQ can never drift
# from the shipped document again (it had been showing 2.99 content at
# version 3.30 -- thirty releases of drift).
#
#   sh scripts/build-faq-pages.sh
set -eu
cd "$(dirname "$0")/.."

if ! command -v texlua >/dev/null 2>&1; then
    echo "texlua not found -- run: sh scripts/dev-setup.sh" >&2
    exit 1
fi

HELPER="$(mktemp)"
trap 'rm -f "$HELPER"' EXIT
cat > "$HELPER" <<'LUAEOF'
local function ReadAll(path)
    local f = assert(io.open(path, "r"))
    local c = f:read("*a")
    f:close()
    return c
end

local md = ReadAll("FAQ.md")

-- Newest changelog entry: first "### x.y ..." block under ## Changelog.
local changelog = md:match("## Changelog\n(.*)$") or ""
local firstHeader, firstBody = changelog:match("### ([^\n]+)\n(.-)\n### ")
if not firstHeader then
    firstHeader, firstBody = changelog:match("### ([^\n]+)\n(.*)$")
end

-- FAQ questions: "### Question?" blocks between ## FAQ and ## Changelog,
-- each tagged with the nearest preceding "## Category" header so the
-- in-game viewer can group/jump by category instead of being one long
-- linear Prev/Next chain.
local faqSection = md:match("## FAQ\n(.-)\n## Changelog") or ""
local qas = {}
local categories = {}
local currentCategory = "General"
for kind, header, body in faqSection:gmatch("(#+) ([^\n]+)\n(.-)\n?%f[#\0]") do
    if kind == "##" then
        currentCategory = header
        categories[#categories + 1] = header
    elseif kind == "###" then
        local a = body:gsub("^%s+", ""):gsub("%s+$", "")
        if header ~= "" and a ~= "" then
            qas[#qas + 1] = { q = header, a = a, category = currentCategory }
        end
    end
end

-- Markdown -> plain in-game text: strip bold/code markers, keep lists.
local function Plain(s)
    s = s:gsub("%*%*(.-)%*%*", "%1"):gsub("`(.-)`", "%1")
    s = s:gsub("%[([^%]]-)%]%(([^%)]-)%)", "%1")
    return s
end

-- Wrap long lines so pages fit without scrolling (the view is ~70 chars).
local function Wrap(text, out)
    for line in (text .. "\n"):gmatch("(.-)\n") do
        line = Plain(line)
        while #line > 74 do
            local cut = 74
            for i = 74, 40, -1 do
                if line:sub(i, i) == " " then cut = i break end
            end
            out[#out + 1] = line:sub(1, cut - (line:sub(cut, cut) == " " and 1 or 0))
            line = line:sub(cut + 1):gsub("^%s+", "")
        end
        out[#out + 1] = line
    end
    -- trim trailing blank lines
    while #out > 0 and out[#out] == "" do out[#out] = nil end
end

local out = {}
local function emit(s) out[#out + 1] = s end
emit("-- EbonBuilds: modules/data/FAQContent.lua")
emit("-- GENERATED by scripts/build-faq-pages.sh from FAQ.md -- do not edit")
emit("-- by hand; edit FAQ.md and re-run the script (release.sh does).")
emit("")
emit("EbonBuilds.FAQContent = { PAGES = {")

local function emitPage(title, bodyLines, category)
    emit("{")
    emit(string.format("    title = %q,", title))
    if category then emit(string.format("    category = %q,", category)) end
    emit("    lines = {")
    for _, l in ipairs(bodyLines) do
        emit(string.format("        %q,", l))
    end
    emit("    },")
    emit("},")
end

if firstHeader then
    local lines = {}
    Wrap(firstBody or "", lines)
    emitPage("What's new: " .. Plain(firstHeader), lines, "What's New")
end
for _, qa in ipairs(qas) do
    local lines = {}
    Wrap(qa.a, lines)
    emitPage(Plain(qa.q), lines, Plain(qa.category))
end
emit("} }")
emit("")
emit("EbonBuilds.FAQContent.CATEGORIES = {")
emit(string.format("    %q,", "What's New"))
for _, c in ipairs(categories) do
    emit(string.format("    %q,", Plain(c)))
end
emit("}")

local f = assert(io.open("modules/data/FAQContent.lua", "w"))
f:write(table.concat(out, "\n") .. "\n")
f:close()
print(string.format("FAQContent.lua: 1 what's-new page + %d FAQ pages.", #qas))
LUAEOF
texlua "$HELPER"
